#pragma config(Sensor, S1,     LightA,         sensorLightActive)
#pragma config(Sensor, S2,     LightB,         sensorLightActive)
#pragma config(Sensor, S3,     color,          sensorColorNxtFULL)
#pragma config(Motor,  motorB,           ,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorA] = 100;
	wait1Msec(5000);
	motor[motorB] = 100;
	wait1Msec(5000);
	motor[motorC] = 30;
	wait1Msec(1000);
}
